# CMAKE generated file: DO NOT EDIT!
# Generated by "MSYS Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /C/msys64/mingw32/bin/cmake.exe

# The command to remove a file.
RM = /C/msys64/mingw32/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /C/Users/katahiromz/Desktop/aa/TypicalProjects/TypicalGtkmmApp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /C/Users/katahiromz/Desktop/aa/TypicalProjects/TypicalGtkmmApp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/C/msys64/mingw32/bin/cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/C/msys64/mingw32/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /C/Users/katahiromz/Desktop/aa/TypicalProjects/TypicalGtkmmApp/CMakeFiles /C/Users/katahiromz/Desktop/aa/TypicalProjects/TypicalGtkmmApp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /C/Users/katahiromz/Desktop/aa/TypicalProjects/TypicalGtkmmApp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TypicalGtkmmApp

# Build rule for target.
TypicalGtkmmApp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TypicalGtkmmApp
.PHONY : TypicalGtkmmApp

# fast build rule for target.
TypicalGtkmmApp/fast:
	$(MAKE) -f CMakeFiles/TypicalGtkmmApp.dir/build.make CMakeFiles/TypicalGtkmmApp.dir/build
.PHONY : TypicalGtkmmApp/fast

# target to build an object file
MainWindow.obj:
	$(MAKE) -f CMakeFiles/TypicalGtkmmApp.dir/build.make CMakeFiles/TypicalGtkmmApp.dir/MainWindow.obj
.PHONY : MainWindow.obj

# target to preprocess a source file
MainWindow.i:
	$(MAKE) -f CMakeFiles/TypicalGtkmmApp.dir/build.make CMakeFiles/TypicalGtkmmApp.dir/MainWindow.i
.PHONY : MainWindow.i

# target to generate assembly for a file
MainWindow.s:
	$(MAKE) -f CMakeFiles/TypicalGtkmmApp.dir/build.make CMakeFiles/TypicalGtkmmApp.dir/MainWindow.s
.PHONY : MainWindow.s

# target to build an object file
TypicalGtkmmApp.obj:
	$(MAKE) -f CMakeFiles/TypicalGtkmmApp.dir/build.make CMakeFiles/TypicalGtkmmApp.dir/TypicalGtkmmApp.obj
.PHONY : TypicalGtkmmApp.obj

# target to preprocess a source file
TypicalGtkmmApp.i:
	$(MAKE) -f CMakeFiles/TypicalGtkmmApp.dir/build.make CMakeFiles/TypicalGtkmmApp.dir/TypicalGtkmmApp.i
.PHONY : TypicalGtkmmApp.i

# target to generate assembly for a file
TypicalGtkmmApp.s:
	$(MAKE) -f CMakeFiles/TypicalGtkmmApp.dir/build.make CMakeFiles/TypicalGtkmmApp.dir/TypicalGtkmmApp.s
.PHONY : TypicalGtkmmApp.s

# target to build an object file
TypicalGtkmmApp_res.obj:
	$(MAKE) -f CMakeFiles/TypicalGtkmmApp.dir/build.make CMakeFiles/TypicalGtkmmApp.dir/TypicalGtkmmApp_res.obj
.PHONY : TypicalGtkmmApp_res.obj

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TypicalGtkmmApp"
	@echo "... MainWindow.obj"
	@echo "... MainWindow.i"
	@echo "... MainWindow.s"
	@echo "... TypicalGtkmmApp.obj"
	@echo "... TypicalGtkmmApp.i"
	@echo "... TypicalGtkmmApp.s"
	@echo "... TypicalGtkmmApp_res.obj"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

